services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: workshop_development
      POSTGRES_USER: workshop
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U workshop -d workshop_development"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      RAILS_ENV: development
    stdin_open: true
    tty: true

volumes:
  postgres_data:
